[package]
edition = "2021"
name    = "bedrock-orm"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono      = "0.4.26"
lazy_static = "1.4.0"
regex       = "1.9.1"
sqlite      = "0.31.0"
thiserror   = "1.0.43"
